---
title: "LEVANTE EF data"
format: html
---

```{r}
library(rlevante) # from https://github.com/levante-framework/rlevante
library(dplyr)
library(stringr)
library(tidyr)
```

```{r}
dataset_spec <- list(list(name = "co_bogota_pilot", version = "v6.0"),
                     list(name = "co_rural_pilot", version = "v4.1"))

participants <- get_participants(dataset_spec)
run_ages <- participants |> select(dataset, user_id, ages) |> unnest(ages)
```

```{r}
ef_tasks <- c("hearts-and-flowers", "memory-game", "same-different-selection")
trials <- get_trials(dataset_spec, tasks = ef_tasks)

trial_data <- trials |>
  left_join(run_ages) |>
  # special for SDS, code too fast/slow RTs as incorrect
  mutate(response_fast = rt_numeric < 200, response_slow = rt_numeric > 2000,
         correct = if_else(task_id == "same-different-selection",
                           correct & !response_fast & !response_slow,
                           correct)) |>
  select(-response_fast, -response_slow)
```

```{r}
surveys <- get_surveys(dataset_spec, survey_types = "caregiver")

ef_variable_pattern <- "SDQ|CBQ|EFQ"
survey_data <- surveys |>
  link_surveys(participants) |>
  filter(str_detect(variable, ef_variable_pattern))
```

```{r}
library(ggplot2)
trial_summary <- trial_data |>
  group_by(dataset, task_id, user_id, age) |>
  summarise(mean_correct = mean(correct))

ggplot(trial_summary, aes(x = age, y = mean_correct)) +
  facet_wrap(vars(task_id)) +
  geom_point() +
  geom_smooth(method = "gam", formula = y ~ s(x, bs = "re")) +
  theme_classic()
```
